### PR TITLE
bump num-complex and rand

### LINKED ISSUE #32: Upgrade `num` dependencies`
With the [update of the num crate to `0.2.0`](https://github.com/rust-num/num/blob/master/RELEASES.md), it would be nice to update the re-exported `num` crate.  Otherwise, there is an incompatibility between the `num::Complex` and `Complex` as re-exported by RustFFT.

This is a breaking change, so it will require an upgrade to `v0.3` of this crate, though this will be an opportunity to complete other breaking changes.

### PR DESCRIPTION
**Pull request by FauxFaux**
Fixes #32.

No changes needed for the num-complex bump. New rand (used only in test) needs the format of an array changing. I hope there are no objections to my chosen seed.

### CODE REVIEW

**Comment by 0xcaff** [comment]
This also removes the dependency on rustc-serialize allowing this library to be used with the wasm32-unknown-unknown target.

**Comment by ejmahler** [comment]
I’m mainly nervous about semver. Is it a breaking change to upgrade a major
version of a public dependency?

I didn’t realize this was a blocker for compiling on wasm, thats definitely
a solid motivation for fixing this

**Comment by 0xcaff** [comment]
The breaking changes are outlined here. I'd bump the version to be safe. https://github.com/rust-num/num-complex/blob/master/RELEASES.md#breaking-changes

**Comment by FauxFaux** [comment]
My 2c is that the `num` people seem to know what they're doing, so if they've bumped, it's probably for a good reason. :)

**Comment by ejmahler** [comment]
Done. I was tempted to upgrade rand all the way to 0.6, but my gut says it's better to leave it at the same version num-complex uses, so that we have fewer versions of the same crate floating around. Especially given that it's only a dependency for tests.

**Pull request merged**
